# Generated by Django 5.2.12 on 2026-03-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('USD', 'EUR'), ('INR', 'INR')], default='USD', max_length=10),
        ),
    ]
